const data = [ {
   "State": "Alabama",
   "Total Number of Workers (in thousands)": 1593,
   "Total Median Weekly Earnings": 753,
   "Total Standard error of median": 14,
   "Women Number of Workers (in thousands)": 712,
   "Women Median weekly earnings": 656,
   "Women Standard error of median": 17,
   "Men Number of workers (in thousands)": 881,
   "Median weekly earnings": 845,
   "Standard error of median": 25,
   "Women's earnings as a percentage of men's": 78,
   "Rating": 46
 },
 {
   "State": "Alaska",
   "Total Number of Workers (in thousands)": 253,
   "Total Median Weekly Earnings": 979,
   "Total Standard error of median": 18,
   "Women Number of Workers (in thousands)": 117,
   "Women Median weekly earnings": 883,
   "Women Standard error of median": 27,
   "Men Number of workers (in thousands)": 136,
   "Median weekly earnings": 1090,
   "Standard error of median": 43,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 30
 },
 {
   "State": "Arizona",
   "Total Number of Workers (in thousands)": 2283,
   "Total Median Weekly Earnings": 830,
   "Total Standard error of median": 17,
   "Women Number of Workers (in thousands)": 970,
   "Women Median weekly earnings": 749,
   "Women Standard error of median": 17,
   "Men Number of workers (in thousands)": 1312,
   "Median weekly earnings": 916,
   "Standard error of median": 26,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 25
 },
 {
   "State": "Arkansas",
   "Total Number of Workers (in thousands)": 1023,
   "Total Median Weekly Earnings": 722,
   "Total Standard error of median": 13,
   "Women Number of Workers (in thousands)": 496,
   "Women Median weekly earnings": 665,
   "Women Standard error of median": 15,
   "Men Number of workers (in thousands)": 527,
   "Median weekly earnings": 799,
   "Standard error of median": 23,
   "Women's earnings as a percentage of men's": 83,
   "Rating": 17
 },
 {
   "State": "California",
   "Total Number of Workers (in thousands)": 13145,
   "Total Median Weekly Earnings": 913,
   "Total Standard error of median": 8,
   "Women Number of Workers (in thousands)": 5620,
   "Women Median weekly earnings": 827,
   "Women Standard error of median": 11,
   "Men Number of workers (in thousands)": 7525,
   "Median weekly earnings": 992,
   "Standard error of median": 11,
   "Women's earnings as a percentage of men's": 83,
   "Rating": 16
 },
 {
   "State": "Colorado",
   "Total Number of Workers (in thousands)": 2049,
   "Total Median Weekly Earnings": 918,
   "Total Standard error of median": 14,
   "Women Number of Workers (in thousands)": 854,
   "Women Median weekly earnings": 838,
   "Women Standard error of median": 20,
   "Men Number of workers (in thousands)": 1195,
   "Median weekly earnings": 986,
   "Standard error of median": 20,
   "Women's earnings as a percentage of men's": 85,
   "Rating": 11
 },
 {
   "State": "Connecticut",
   "Total Number of Workers (in thousands)": 1290,
   "Total Median Weekly Earnings": 1011,
   "Total Standard error of median": 19,
   "Women Number of Workers (in thousands)": 577,
   "Women Median weekly earnings": 938,
   "Women Standard error of median": 40,
   "Men Number of workers (in thousands)": 713,
   "Median weekly earnings": 1102,
   "Standard error of median": 47,
   "Women's earnings as a percentage of men's": 85,
   "Rating": 10
 },
 {
   "State": "Delaware",
   "Total Number of Workers (in thousands)": 349,
   "Total Median Weekly Earnings": 840,
   "Total Standard error of median": 22,
   "Women Number of Workers (in thousands)": 160,
   "Women Median weekly earnings": 785,
   "Women Standard error of median": 19,
   "Men Number of workers (in thousands)": 189,
   "Median weekly earnings": 905,
   "Standard error of median": 26,
   "Women's earnings as a percentage of men's": 87,
   "Rating": 6
 },
 {
   "State": "District of Columbia",
   "Total Number of Workers (in thousands)": 311,
   "Total Median Weekly Earnings": 1273,
   "Total Standard error of median": 30,
   "Women Number of Workers (in thousands)": 158,
   "Women Median weekly earnings": 1191,
   "Women Standard error of median": 45,
   "Men Number of workers (in thousands)": 153,
   "Median weekly earnings": 1385,
   "Standard error of median": 50,
   "Women's earnings as a percentage of men's": 86,
   "Rating": 9
 },
 {
   "State": "Florida",
   "Total Number of Workers (in thousands)": 7092,
   "Total Median Weekly Earnings": 768,
   "Total Standard error of median": 7,
   "Women Number of Workers (in thousands)": 3312,
   "Women Median weekly earnings": 726,
   "Women Standard error of median": 9,
   "Men Number of workers (in thousands)": 3780,
   "Median weekly earnings": 826,
   "Standard error of median": 14,
   "Women's earnings as a percentage of men's": 88,
   "Rating": 3
 },
 {
   "State": "Georgia",
   "Total Number of Workers (in thousands)": 3717,
   "Total Median Weekly Earnings": 775,
   "Total Standard error of median": 12,
   "Women Number of Workers (in thousands)": 1736,
   "Women Median weekly earnings": 720,
   "Women Standard error of median": 17,
   "Men Number of workers (in thousands)": 1981,
   "Median weekly earnings": 866,
   "Standard error of median": 29,
   "Women's earnings as a percentage of men's": 83,
   "Rating": 18
 },
 {
   "State": "Hawaii",
   "Total Number of Workers (in thousands)": 497,
   "Total Median Weekly Earnings": 821,
   "Total Standard error of median": 18,
   "Women Number of Workers (in thousands)": 234,
   "Women Median weekly earnings": 734,
   "Women Standard error of median": 23,
   "Men Number of workers (in thousands)": 263,
   "Median weekly earnings": 918,
   "Standard error of median": 28,
   "Women's earnings as a percentage of men's": 80,
   "Rating": 37
 },
 {
   "State": "Idaho",
   "Total Number of Workers (in thousands)": 568,
   "Total Median Weekly Earnings": 794,
   "Total Standard error of median": 16,
   "Women Number of Workers (in thousands)": 230,
   "Women Median weekly earnings": 695,
   "Women Standard error of median": 13,
   "Men Number of workers (in thousands)": 338,
   "Median weekly earnings": 893,
   "Standard error of median": 17,
   "Women's earnings as a percentage of men's": 78,
   "Rating": 44
 },
 {
   "State": "Illinois",
   "Total Number of Workers (in thousands)": 4426,
   "Total Median Weekly Earnings": 918,
   "Total Standard error of median": 12,
   "Women Number of Workers (in thousands)": 1965,
   "Women Median weekly earnings": 791,
   "Women Standard error of median": 16,
   "Men Number of workers (in thousands)": 2460,
   "Median weekly earnings": 1017,
   "Standard error of median": 17,
   "Women's earnings as a percentage of men's": 78,
   "Rating": 43
 },
 {
   "State": "Indiana",
   "Total Number of Workers (in thousands)": 2425,
   "Total Median Weekly Earnings": 805,
   "Total Standard error of median": 14,
   "Women Number of Workers (in thousands)": 1075,
   "Women Median weekly earnings": 708,
   "Women Standard error of median": 19,
   "Men Number of workers (in thousands)": 1350,
   "Median weekly earnings": 903,
   "Standard error of median": 28,
   "Women's earnings as a percentage of men's": 78,
   "Rating": 42
 },
 {
   "State": "Iowa",
   "Total Number of Workers (in thousands)": 1167,
   "Total Median Weekly Earnings": 825,
   "Total Standard error of median": 15,
   "Women Number of Workers (in thousands)": 522,
   "Women Median weekly earnings": 738,
   "Women Standard error of median": 17,
   "Men Number of workers (in thousands)": 645,
   "Median weekly earnings": 907,
   "Standard error of median": 20,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 28
 },
 {
   "State": "Kansas",
   "Total Number of Workers (in thousands)": 1040,
   "Total Median Weekly Earnings": 823,
   "Total Standard error of median": 18,
   "Women Number of Workers (in thousands)": 459,
   "Women Median weekly earnings": 749,
   "Women Standard error of median": 20,
   "Men Number of workers (in thousands)": 581,
   "Median weekly earnings": 916,
   "Standard error of median": 21,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 24
 },
 {
   "State": "Kentucky",
   "Total Number of Workers (in thousands)": 1477,
   "Total Median Weekly Earnings": 774,
   "Total Standard error of median": 15,
   "Women Number of Workers (in thousands)": 676,
   "Women Median weekly earnings": 673,
   "Women Standard error of median": 20,
   "Men Number of workers (in thousands)": 801,
   "Median weekly earnings": 834,
   "Standard error of median": 30,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 34
 },
 {
   "State": "Louisiana",
   "Total Number of Workers (in thousands)": 1498,
   "Total Median Weekly Earnings": 773,
   "Total Standard error of median": 15,
   "Women Number of Workers (in thousands)": 673,
   "Women Median weekly earnings": 686,
   "Women Standard error of median": 20,
   "Men Number of workers (in thousands)": 825,
   "Median weekly earnings": 886,
   "Standard error of median": 26,
   "Women's earnings as a percentage of men's": 77,
   "Rating": 48
 },
 {
   "State": "Maine",
   "Total Number of Workers (in thousands)": 445,
   "Total Median Weekly Earnings": 845,
   "Total Standard error of median": 24,
   "Women Number of Workers (in thousands)": 201,
   "Women Median weekly earnings": 760,
   "Women Standard error of median": 23,
   "Men Number of workers (in thousands)": 244,
   "Median weekly earnings": 911,
   "Standard error of median": 22,
   "Women's earnings as a percentage of men's": 83,
   "Rating": 15
 },
 {
   "State": "Maryland",
   "Total Number of Workers (in thousands)": 2295,
   "Total Median Weekly Earnings": 1036,
   "Total Standard error of median": 28,
   "Women Number of Workers (in thousands)": 1041,
   "Women Median weekly earnings": 959,
   "Women Standard error of median": 37,
   "Men Number of workers (in thousands)": 1254,
   "Median weekly earnings": 1131,
   "Standard error of median": 41,
   "Women's earnings as a percentage of men's": 85,
   "Rating": 12
 },
 {
   "State": "Massachusetts",
   "Total Number of Workers (in thousands)": 2597,
   "Total Median Weekly Earnings": 1078,
   "Total Standard error of median": 21,
   "Women Number of Workers (in thousands)": 1157,
   "Women Median weekly earnings": 971,
   "Women Standard error of median": 18,
   "Men Number of workers (in thousands)": 1440,
   "Median weekly earnings": 1204,
   "Standard error of median": 32,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 35
 },
 {
   "State": "Michigan",
   "Total Number of Workers (in thousands)": 3405,
   "Total Median Weekly Earnings": 853,
   "Total Standard error of median": 16,
   "Women Number of Workers (in thousands)": 1455,
   "Women Median weekly earnings": 765,
   "Women Standard error of median": 12,
   "Men Number of workers (in thousands)": 1950,
   "Median weekly earnings": 928,
   "Standard error of median": 17,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 20
 },
 {
   "State": "Minnesota",
   "Total Number of Workers (in thousands)": 2128,
   "Total Median Weekly Earnings": 955,
   "Total Standard error of median": 20,
   "Women Number of Workers (in thousands)": 937,
   "Women Median weekly earnings": 844,
   "Women Standard error of median": 26,
   "Men Number of workers (in thousands)": 1191,
   "Median weekly earnings": 1026,
   "Standard error of median": 24,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 21
 },
 {
   "State": "Mississippi",
   "Total Number of Workers (in thousands)": 944,
   "Total Median Weekly Earnings": 723,
   "Total Standard error of median": 13,
   "Women Number of Workers (in thousands)": 454,
   "Women Median weekly earnings": 643,
   "Women Standard error of median": 18,
   "Men Number of workers (in thousands)": 490,
   "Median weekly earnings": 794,
   "Standard error of median": 25,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 29
 },
 {
   "State": "Missouri",
   "Total Number of Workers (in thousands)": 2166,
   "Total Median Weekly Earnings": 826,
   "Total Standard error of median": 17,
   "Women Number of Workers (in thousands)": 1006,
   "Women Median weekly earnings": 733,
   "Women Standard error of median": 20,
   "Men Number of workers (in thousands)": 1160,
   "Median weekly earnings": 925,
   "Standard error of median": 27,
   "Women's earnings as a percentage of men's": 79,
   "Rating": 39
 },
 {
   "State": "Montana",
   "Total Number of Workers (in thousands)": 321,
   "Total Median Weekly Earnings": 800,
   "Total Standard error of median": 19,
   "Women Number of Workers (in thousands)": 135,
   "Women Median weekly earnings": 713,
   "Women Standard error of median": 15,
   "Men Number of workers (in thousands)": 185,
   "Median weekly earnings": 883,
   "Standard error of median": 22,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 33
 },
 {
   "State": "Nebraska",
   "Total Number of Workers (in thousands)": 696,
   "Total Median Weekly Earnings": 814,
   "Total Standard error of median": 16,
   "Women Number of Workers (in thousands)": 311,
   "Women Median weekly earnings": 760,
   "Women Standard error of median": 23,
   "Men Number of workers (in thousands)": 385,
   "Median weekly earnings": 871,
   "Standard error of median": 28,
   "Women's earnings as a percentage of men's": 87,
   "Rating": 4
 },
 {
   "State": "Nevada",
   "Total Number of Workers (in thousands)": 1071,
   "Total Median Weekly Earnings": 746,
   "Total Standard error of median": 12,
   "Women Number of Workers (in thousands)": 451,
   "Women Median weekly earnings": 675,
   "Women Standard error of median": 14,
   "Men Number of workers (in thousands)": 621,
   "Median weekly earnings": 808,
   "Standard error of median": 16,
   "Women's earnings as a percentage of men's": 84,
   "Rating": 14
 },
 {
   "State": "New Hampshire",
   "Total Number of Workers (in thousands)": 512,
   "Total Median Weekly Earnings": 918,
   "Total Standard error of median": 20,
   "Women Number of Workers (in thousands)": 225,
   "Women Median weekly earnings": 838,
   "Women Standard error of median": 21,
   "Men Number of workers (in thousands)": 287,
   "Median weekly earnings": 1003,
   "Standard error of median": 25,
   "Women's earnings as a percentage of men's": 84,
   "Rating": 13
 },
 {
   "State": "New Jersey",
   "Total Number of Workers (in thousands)": 3241,
   "Total Median Weekly Earnings": 1016,
   "Total Standard error of median": 13,
   "Women Number of Workers (in thousands)": 1486,
   "Women Median weekly earnings": 929,
   "Women Standard error of median": 17,
   "Men Number of workers (in thousands)": 1755,
   "Median weekly earnings": 1138,
   "Standard error of median": 23,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 26
 },
 {
   "State": "New Mexico",
   "Total Number of Workers (in thousands)": 622,
   "Total Median Weekly Earnings": 737,
   "Total Standard error of median": 13,
   "Women Number of Workers (in thousands)": 268,
   "Women Median weekly earnings": 701,
   "Women Standard error of median": 16,
   "Men Number of workers (in thousands)": 354,
   "Median weekly earnings": 771,
   "Standard error of median": 22,
   "Women's earnings as a percentage of men's": 91,
   "Rating": 1
 },
 {
   "State": "New York",
   "Total Number of Workers (in thousands)": 7120,
   "Total Median Weekly Earnings": 918,
   "Total Standard error of median": 9,
   "Women Number of Workers (in thousands)": 3303,
   "Women Median weekly earnings": 850,
   "Women Standard error of median": 15,
   "Men Number of workers (in thousands)": 3817,
   "Median weekly earnings": 984,
   "Standard error of median": 13,
   "Women's earnings as a percentage of men's": 86,
   "Rating": 7
 },
 {
   "State": "North Carolina",
   "Total Number of Workers (in thousands)": 3574,
   "Total Median Weekly Earnings": 810,
   "Total Standard error of median": 10,
   "Women Number of Workers (in thousands)": 1655,
   "Women Median weekly earnings": 754,
   "Women Standard error of median": 13,
   "Men Number of workers (in thousands)": 1919,
   "Median weekly earnings": 874,
   "Standard error of median": 19,
   "Women's earnings as a percentage of men's": 86,
   "Rating": 8
 },
 {
   "State": "North Dakota",
   "Total Number of Workers (in thousands)": 291,
   "Total Median Weekly Earnings": 857,
   "Total Standard error of median": 18,
   "Women Number of Workers (in thousands)": 128,
   "Women Median weekly earnings": 740,
   "Women Standard error of median": 18,
   "Men Number of workers (in thousands)": 164,
   "Median weekly earnings": 952,
   "Standard error of median": 18,
   "Women's earnings as a percentage of men's": 78,
   "Rating": 45
 },
 {
   "State": "Ohio",
   "Total Number of Workers (in thousands)": 4021,
   "Total Median Weekly Earnings": 832,
   "Total Standard error of median": 12,
   "Women Number of Workers (in thousands)": 1801,
   "Women Median weekly earnings": 743,
   "Women Standard error of median": 13,
   "Men Number of workers (in thousands)": 2220,
   "Median weekly earnings": 908,
   "Standard error of median": 15,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 23
 },
 {
   "State": "Oklahoma",
   "Total Number of Workers (in thousands)": 1308,
   "Total Median Weekly Earnings": 766,
   "Total Standard error of median": 11,
   "Women Number of Workers (in thousands)": 554,
   "Women Median weekly earnings": 685,
   "Women Standard error of median": 16,
   "Men Number of workers (in thousands)": 754,
   "Median weekly earnings": 859,
   "Standard error of median": 25,
   "Women's earnings as a percentage of men's": 80,
   "Rating": 38
 },
 {
   "State": "Oregon",
   "Total Number of Workers (in thousands)": 1413,
   "Total Median Weekly Earnings": 873,
   "Total Standard error of median": 23,
   "Women Number of Workers (in thousands)": 604,
   "Women Median weekly earnings": 770,
   "Women Standard error of median": 24,
   "Men Number of workers (in thousands)": 810,
   "Median weekly earnings": 945,
   "Standard error of median": 22,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 27
 },
 {
   "State": "Pennsylvania",
   "Total Number of Workers (in thousands)": 4448,
   "Total Median Weekly Earnings": 869,
   "Total Standard error of median": 13,
   "Women Number of Workers (in thousands)": 1985,
   "Women Median weekly earnings": 768,
   "Women Standard error of median": 11,
   "Men Number of workers (in thousands)": 2463,
   "Median weekly earnings": 971,
   "Standard error of median": 17,
   "Women's earnings as a percentage of men's": 79,
   "Rating": 41
 },
 {
   "State": "Rhode Island",
   "Total Number of Workers (in thousands)": 391,
   "Total Median Weekly Earnings": 897,
   "Total Standard error of median": 14,
   "Women Number of Workers (in thousands)": 178,
   "Women Median weekly earnings": 833,
   "Women Standard error of median": 24,
   "Men Number of workers (in thousands)": 213,
   "Median weekly earnings": 956,
   "Standard error of median": 32,
   "Women's earnings as a percentage of men's": 87,
   "Rating": 5
 },
 {
   "State": "South Carolina",
   "Total Number of Workers (in thousands)": 1673,
   "Total Median Weekly Earnings": 799,
   "Total Standard error of median": 14,
   "Women Number of Workers (in thousands)": 753,
   "Women Median weekly earnings": 696,
   "Women Standard error of median": 16,
   "Men Number of workers (in thousands)": 920,
   "Median weekly earnings": 898,
   "Standard error of median": 20,
   "Women's earnings as a percentage of men's": 78,
   "Rating": 47
 },
 {
   "State": "South Dakota",
   "Total Number of Workers (in thousands)": 308,
   "Total Median Weekly Earnings": 769,
   "Total Standard error of median": 13,
   "Women Number of Workers (in thousands)": 141,
   "Women Median weekly earnings": 679,
   "Women Standard error of median": 15,
   "Men Number of workers (in thousands)": 168,
   "Median weekly earnings": 858,
   "Standard error of median": 19,
   "Women's earnings as a percentage of men's": 79,
   "Rating": 40
 },
 {
   "State": "Tennessee",
   "Total Number of Workers (in thousands)": 2291,
   "Total Median Weekly Earnings": 780,
   "Total Standard error of median": 15,
   "Women Number of Workers (in thousands)": 1034,
   "Women Median weekly earnings": 704,
   "Women Standard error of median": 17,
   "Men Number of workers (in thousands)": 1257,
   "Median weekly earnings": 874,
   "Standard error of median": 23,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 36
 },
 {
   "State": "Texas",
   "Total Number of Workers (in thousands)": 9918,
   "Total Median Weekly Earnings": 813,
   "Total Standard error of median": 9,
   "Women Number of Workers (in thousands)": 4243,
   "Women Median weekly earnings": 734,
   "Women Standard error of median": 9,
   "Men Number of workers (in thousands)": 5675,
   "Median weekly earnings": 894,
   "Standard error of median": 11,
   "Women's earnings as a percentage of men's": 82,
   "Rating": 22
 },
 {
   "State": "Utah",
   "Total Number of Workers (in thousands)": 1044,
   "Total Median Weekly Earnings": 827,
   "Total Standard error of median": 15,
   "Women Number of Workers (in thousands)": 394,
   "Women Median weekly earnings": 692,
   "Women Standard error of median": 14,
   "Men Number of workers (in thousands)": 650,
   "Median weekly earnings": 952,
   "Standard error of median": 18,
   "Women's earnings as a percentage of men's": 73,
   "Rating": 50
 },
 {
   "State": "Vermont",
   "Total Number of Workers (in thousands)": 227,
   "Total Median Weekly Earnings": 874,
   "Total Standard error of median": 19,
   "Women Number of Workers (in thousands)": 103,
   "Women Median weekly earnings": 816,
   "Women Standard error of median": 24,
   "Men Number of workers (in thousands)": 124,
   "Median weekly earnings": 918,
   "Standard error of median": 21,
   "Women's earnings as a percentage of men's": 89,
   "Rating": 2
 },
 {
   "State": "Virginia",
   "Total Number of Workers (in thousands)": 3134,
   "Total Median Weekly Earnings": 937,
   "Total Standard error of median": 18,
   "Women Number of Workers (in thousands)": 1414,
   "Women Median weekly earnings": 844,
   "Women Standard error of median": 20,
   "Men Number of workers (in thousands)": 1720,
   "Median weekly earnings": 1043,
   "Standard error of median": 33,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 31
 },
 {
   "State": "Washington",
   "Total Number of Workers (in thousands)": 2538,
   "Total Median Weekly Earnings": 961,
   "Total Standard error of median": 20,
   "Women Number of Workers (in thousands)": 1066,
   "Women Median weekly earnings": 825,
   "Women Standard error of median": 22,
   "Men Number of workers (in thousands)": 1472,
   "Median weekly earnings": 1093,
   "Standard error of median": 27,
   "Women's earnings as a percentage of men's": 76,
   "Rating": 49
 },
 {
   "State": "West Virginia",
   "Total Number of Workers (in thousands)": 569,
   "Total Median Weekly Earnings": 747,
   "Total Standard error of median": 12,
   "Women Number of Workers (in thousands)": 253,
   "Women Median weekly earnings": 670,
   "Women Standard error of median": 20,
   "Men Number of workers (in thousands)": 316,
   "Median weekly earnings": 830,
   "Standard error of median": 22,
   "Women's earnings as a percentage of men's": 81,
   "Rating": 32
 },
 {
   "State": "Wisconsin",
   "Total Number of Workers (in thousands)": 2159,
   "Total Median Weekly Earnings": 860,
   "Total Standard error of median": 13,
   "Women Number of Workers (in thousands)": 926,
   "Women Median weekly earnings": 777,
   "Women Standard error of median": 18,
   "Men Number of workers (in thousands)": 1233,
   "Median weekly earnings": 936,
   "Standard error of median": 21,
   "Women's earnings as a percentage of men's": 83,
   "Rating": 19
 },
 {
   "State": "Wyoming",
   "Total Number of Workers (in thousands)": 197,
   "Total Median Weekly Earnings": 875,
   "Total Standard error of median": 21,
   "Women Number of Workers (in thousands)": 82,
   "Women Median weekly earnings": 720,
   "Women Standard error of median": 17,
   "Men Number of workers (in thousands)": 115,
   "Median weekly earnings": 1006,
   "Standard error of median": 21,
   "Women's earnings as a percentage of men's": 72,
   "Rating": 51
 }
]